apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digest-lueurxax-org
  namespace: digest
spec:
  secretName: digest-lueurxax-org-tls
  dnsNames:
  - digest.lueurxax.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
